name: Nightly Build with PyInstaller

on:
    push:
        branches: [ "master" ]
    workflow_run:
        workflows: [ "Flake8 Style Check" ]
        types: [ completed ]

permissions:
    contents: write

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ windows-latest, macos-latest, ubuntu-latest ]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install flake8, pyinstaller

            - name: Linting
              run: flake8 .

            - name: Build with PyInstaller
              run: |
                  pyinstaller --onefile download.py

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.os }}-download
                  path: 'download*'
                  if-no-files-found: error
                  overwrite: true

    release:
        runs-on: ubuntu-latest

        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts
                  merge-multiple: true

            - name: Create Nightly Release
              uses: ncipollo/release-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: nightly-${{ github.run_id }}
                  name: 'Nightly Build - ${{ github.run_id }}'
                  draft: false
                  prerelease: true
                  artifacts: 'artifacts/*'

