name: Flake8 Style Check

on:
    push:
        branches: [ '**' ]
        branches-ignore: [ 'master' ]
    pull_request:
        branches: [ '**' ]

jobs:
    flake8:
        runs-on: ubuntu-latest
        # prevent double-up for commits to a branch with an open PR
        if: github.event_name == 'pull_request' || github.event_name == 'push' && github.ref != 'refs/heads/master'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8

            - name: Run Flake8
              run: flake8 .
